// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.1
// source: api/stat/stat.proto

package stat

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Outlier struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommandId     string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	Value         int64                  `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Outlier) Reset() {
	*x = Outlier{}
	mi := &file_api_stat_stat_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Outlier) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Outlier) ProtoMessage() {}

func (x *Outlier) ProtoReflect() protoreflect.Message {
	mi := &file_api_stat_stat_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Outlier.ProtoReflect.Descriptor instead.
func (*Outlier) Descriptor() ([]byte, []int) {
	return file_api_stat_stat_proto_rawDescGZIP(), []int{0}
}

func (x *Outlier) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *Outlier) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type Stat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Count         int64                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	CountsByValue []*Stat_Value          `protobuf:"bytes,3,rep,name=counts_by_value,json=countsByValue,proto3" json:"counts_by_value,omitempty"`
	Outliers      []*Outlier             `protobuf:"bytes,4,rep,name=outliers,proto3" json:"outliers,omitempty"`
	Median        int64                  `protobuf:"varint,5,opt,name=median,proto3" json:"median,omitempty"`
	Percentile75  int64                  `protobuf:"varint,6,opt,name=percentile75,proto3" json:"percentile75,omitempty"`
	Percentile85  int64                  `protobuf:"varint,7,opt,name=percentile85,proto3" json:"percentile85,omitempty"`
	Percentile95  int64                  `protobuf:"varint,8,opt,name=percentile95,proto3" json:"percentile95,omitempty"`
	Average       float64                `protobuf:"fixed64,9,opt,name=average,proto3" json:"average,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Stat) Reset() {
	*x = Stat{}
	mi := &file_api_stat_stat_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Stat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Stat) ProtoMessage() {}

func (x *Stat) ProtoReflect() protoreflect.Message {
	mi := &file_api_stat_stat_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Stat.ProtoReflect.Descriptor instead.
func (*Stat) Descriptor() ([]byte, []int) {
	return file_api_stat_stat_proto_rawDescGZIP(), []int{1}
}

func (x *Stat) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Stat) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *Stat) GetCountsByValue() []*Stat_Value {
	if x != nil {
		return x.CountsByValue
	}
	return nil
}

func (x *Stat) GetOutliers() []*Outlier {
	if x != nil {
		return x.Outliers
	}
	return nil
}

func (x *Stat) GetMedian() int64 {
	if x != nil {
		return x.Median
	}
	return 0
}

func (x *Stat) GetPercentile75() int64 {
	if x != nil {
		return x.Percentile75
	}
	return 0
}

func (x *Stat) GetPercentile85() int64 {
	if x != nil {
		return x.Percentile85
	}
	return 0
}

func (x *Stat) GetPercentile95() int64 {
	if x != nil {
		return x.Percentile95
	}
	return 0
}

func (x *Stat) GetAverage() float64 {
	if x != nil {
		return x.Average
	}
	return 0
}

type Stat_Value struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Count         int64                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Stat_Value) Reset() {
	*x = Stat_Value{}
	mi := &file_api_stat_stat_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Stat_Value) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Stat_Value) ProtoMessage() {}

func (x *Stat_Value) ProtoReflect() protoreflect.Message {
	mi := &file_api_stat_stat_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Stat_Value.ProtoReflect.Descriptor instead.
func (*Stat_Value) Descriptor() ([]byte, []int) {
	return file_api_stat_stat_proto_rawDescGZIP(), []int{1, 0}
}

func (x *Stat_Value) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Stat_Value) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

var File_api_stat_stat_proto protoreflect.FileDescriptor

const file_api_stat_stat_proto_rawDesc = "" +
	"\n" +
	"\x13api/stat/stat.proto\x12\x05stats\">\n" +
	"\aOutlier\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value\"\xe8\x02\n" +
	"\x04Stat\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x03R\x05count\x129\n" +
	"\x0fcounts_by_value\x18\x03 \x03(\v2\x11.stats.Stat.ValueR\rcountsByValue\x12*\n" +
	"\boutliers\x18\x04 \x03(\v2\x0e.stats.OutlierR\boutliers\x12\x16\n" +
	"\x06median\x18\x05 \x01(\x03R\x06median\x12\"\n" +
	"\fpercentile75\x18\x06 \x01(\x03R\fpercentile75\x12\"\n" +
	"\fpercentile85\x18\a \x01(\x03R\fpercentile85\x12\"\n" +
	"\fpercentile95\x18\b \x01(\x03R\fpercentile95\x12\x18\n" +
	"\aaverage\x18\t \x01(\x01R\aaverage\x1a1\n" +
	"\x05Value\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x03R\x05countB)Z'github.com/bazelbuild/reclient/api/statb\x06proto3"

var (
	file_api_stat_stat_proto_rawDescOnce sync.Once
	file_api_stat_stat_proto_rawDescData []byte
)

func file_api_stat_stat_proto_rawDescGZIP() []byte {
	file_api_stat_stat_proto_rawDescOnce.Do(func() {
		file_api_stat_stat_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_stat_stat_proto_rawDesc), len(file_api_stat_stat_proto_rawDesc)))
	})
	return file_api_stat_stat_proto_rawDescData
}

var file_api_stat_stat_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_api_stat_stat_proto_goTypes = []any{
	(*Outlier)(nil),    // 0: stats.Outlier
	(*Stat)(nil),       // 1: stats.Stat
	(*Stat_Value)(nil), // 2: stats.Stat.Value
}
var file_api_stat_stat_proto_depIdxs = []int32{
	2, // 0: stats.Stat.counts_by_value:type_name -> stats.Stat.Value
	0, // 1: stats.Stat.outliers:type_name -> stats.Outlier
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_stat_stat_proto_init() }
func file_api_stat_stat_proto_init() {
	if File_api_stat_stat_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_stat_stat_proto_rawDesc), len(file_api_stat_stat_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_stat_stat_proto_goTypes,
		DependencyIndexes: file_api_stat_stat_proto_depIdxs,
		MessageInfos:      file_api_stat_stat_proto_msgTypes,
	}.Build()
	File_api_stat_stat_proto = out.File
	file_api_stat_stat_proto_goTypes = nil
	file_api_stat_stat_proto_depIdxs = nil
}
