#include "stable_status.h"

#ifndef _INTERNAL_PKG_VERSION_VERSION_H
#define _INTERNAL_PKG_VERSION_VERSION_H
#define RECLIENT_VERSION                            \
  "{VERSION_MAJOR}.{VERSION_MINOR}.{VERSION_PATCH}" \
  "." STABLE_VERSION_SHA
#define INPUT_PROCESSOR "{INPUT_PROCESSOR}"
#endif
