// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.1
// source: api/auth/auth.proto

package auth

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AuthMechanism_Value int32

const (
	AuthMechanism_UNSPECIFIED       AuthMechanism_Value = 0
	AuthMechanism_ADC               AuthMechanism_Value = 2
	AuthMechanism_GCE               AuthMechanism_Value = 4
	AuthMechanism_CREDENTIAL_FILE   AuthMechanism_Value = 5
	AuthMechanism_NONE              AuthMechanism_Value = 6
	AuthMechanism_CREDENTIALSHELPER AuthMechanism_Value = 7
)

// Enum value maps for AuthMechanism_Value.
var (
	AuthMechanism_Value_name = map[int32]string{
		0: "UNSPECIFIED",
		2: "ADC",
		4: "GCE",
		5: "CREDENTIAL_FILE",
		6: "NONE",
		7: "CREDENTIALSHELPER",
	}
	AuthMechanism_Value_value = map[string]int32{
		"UNSPECIFIED":       0,
		"ADC":               2,
		"GCE":               4,
		"CREDENTIAL_FILE":   5,
		"NONE":              6,
		"CREDENTIALSHELPER": 7,
	}
)

func (x AuthMechanism_Value) Enum() *AuthMechanism_Value {
	p := new(AuthMechanism_Value)
	*p = x
	return p
}

func (x AuthMechanism_Value) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AuthMechanism_Value) Descriptor() protoreflect.EnumDescriptor {
	return file_api_auth_auth_proto_enumTypes[0].Descriptor()
}

func (AuthMechanism_Value) Type() protoreflect.EnumType {
	return &file_api_auth_auth_proto_enumTypes[0]
}

func (x AuthMechanism_Value) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AuthMechanism_Value.Descriptor instead.
func (AuthMechanism_Value) EnumDescriptor() ([]byte, []int) {
	return file_api_auth_auth_proto_rawDescGZIP(), []int{0, 0}
}

type AuthMechanism struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthMechanism) Reset() {
	*x = AuthMechanism{}
	mi := &file_api_auth_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthMechanism) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthMechanism) ProtoMessage() {}

func (x *AuthMechanism) ProtoReflect() protoreflect.Message {
	mi := &file_api_auth_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthMechanism.ProtoReflect.Descriptor instead.
func (*AuthMechanism) Descriptor() ([]byte, []int) {
	return file_api_auth_auth_proto_rawDescGZIP(), []int{0}
}

type Credentials struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Mechanism            AuthMechanism_Value    `protobuf:"varint,1,opt,name=mechanism,proto3,enum=auth.AuthMechanism_Value" json:"mechanism,omitempty"`
	Token                string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	Expiry               *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=expiry,proto3" json:"expiry,omitempty"`
	RefreshExpiry        *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=refresh_expiry,json=refreshExpiry,proto3" json:"refresh_expiry,omitempty"`
	CredsHelperCmdDigest string                 `protobuf:"bytes,6,opt,name=credsHelperCmdDigest,proto3" json:"credsHelperCmdDigest,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *Credentials) Reset() {
	*x = Credentials{}
	mi := &file_api_auth_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Credentials) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Credentials) ProtoMessage() {}

func (x *Credentials) ProtoReflect() protoreflect.Message {
	mi := &file_api_auth_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Credentials.ProtoReflect.Descriptor instead.
func (*Credentials) Descriptor() ([]byte, []int) {
	return file_api_auth_auth_proto_rawDescGZIP(), []int{1}
}

func (x *Credentials) GetMechanism() AuthMechanism_Value {
	if x != nil {
		return x.Mechanism
	}
	return AuthMechanism_UNSPECIFIED
}

func (x *Credentials) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *Credentials) GetExpiry() *timestamppb.Timestamp {
	if x != nil {
		return x.Expiry
	}
	return nil
}

func (x *Credentials) GetRefreshExpiry() *timestamppb.Timestamp {
	if x != nil {
		return x.RefreshExpiry
	}
	return nil
}

func (x *Credentials) GetCredsHelperCmdDigest() string {
	if x != nil {
		return x.CredsHelperCmdDigest
	}
	return ""
}

var File_api_auth_auth_proto protoreflect.FileDescriptor

const file_api_auth_auth_proto_rawDesc = "" +
	"\n" +
	"\x13api/auth/auth.proto\x12\x04auth\x1a\x1fgoogle/protobuf/timestamp.proto\"}\n" +
	"\rAuthMechanism\"l\n" +
	"\x05Value\x12\x0f\n" +
	"\vUNSPECIFIED\x10\x00\x12\a\n" +
	"\x03ADC\x10\x02\x12\a\n" +
	"\x03GCE\x10\x04\x12\x13\n" +
	"\x0fCREDENTIAL_FILE\x10\x05\x12\b\n" +
	"\x04NONE\x10\x06\x12\x15\n" +
	"\x11CREDENTIALSHELPER\x10\a\"\x04\b\x01\x10\x01\"\x04\b\x03\x10\x03\"\x99\x02\n" +
	"\vCredentials\x127\n" +
	"\tmechanism\x18\x01 \x01(\x0e2\x19.auth.AuthMechanism.ValueR\tmechanism\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x122\n" +
	"\x06expiry\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x06expiry\x12A\n" +
	"\x0erefresh_expiry\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\rrefreshExpiry\x122\n" +
	"\x14credsHelperCmdDigest\x18\x06 \x01(\tR\x14credsHelperCmdDigestJ\x04\b\x03\x10\x04R\n" +
	"created_atB)Z'github.com/bazelbuild/reclient/api/authb\x06proto3"

var (
	file_api_auth_auth_proto_rawDescOnce sync.Once
	file_api_auth_auth_proto_rawDescData []byte
)

func file_api_auth_auth_proto_rawDescGZIP() []byte {
	file_api_auth_auth_proto_rawDescOnce.Do(func() {
		file_api_auth_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_auth_auth_proto_rawDesc), len(file_api_auth_auth_proto_rawDesc)))
	})
	return file_api_auth_auth_proto_rawDescData
}

var file_api_auth_auth_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_auth_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_auth_auth_proto_goTypes = []any{
	(AuthMechanism_Value)(0),      // 0: auth.AuthMechanism.Value
	(*AuthMechanism)(nil),         // 1: auth.AuthMechanism
	(*Credentials)(nil),           // 2: auth.Credentials
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
}
var file_api_auth_auth_proto_depIdxs = []int32{
	0, // 0: auth.Credentials.mechanism:type_name -> auth.AuthMechanism.Value
	3, // 1: auth.Credentials.expiry:type_name -> google.protobuf.Timestamp
	3, // 2: auth.Credentials.refresh_expiry:type_name -> google.protobuf.Timestamp
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_api_auth_auth_proto_init() }
func file_api_auth_auth_proto_init() {
	if File_api_auth_auth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_auth_auth_proto_rawDesc), len(file_api_auth_auth_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_auth_auth_proto_goTypes,
		DependencyIndexes: file_api_auth_auth_proto_depIdxs,
		EnumInfos:         file_api_auth_auth_proto_enumTypes,
		MessageInfos:      file_api_auth_auth_proto_msgTypes,
	}.Build()
	File_api_auth_auth_proto = out.File
	file_api_auth_auth_proto_goTypes = nil
	file_api_auth_auth_proto_depIdxs = nil
}
