// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.1
// source: api/scandeps/cppscandeps.proto

package scandeps

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CPPDepsScanner_ProcessInputs_FullMethodName = "/scandeps.CPPDepsScanner/ProcessInputs"
	CPPDepsScanner_Status_FullMethodName        = "/scandeps.CPPDepsScanner/Status"
	CPPDepsScanner_Shutdown_FullMethodName      = "/scandeps.CPPDepsScanner/Shutdown"
	CPPDepsScanner_Capabilities_FullMethodName  = "/scandeps.CPPDepsScanner/Capabilities"
)

// CPPDepsScannerClient is the client API for CPPDepsScanner service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CPPDepsScannerClient interface {
	ProcessInputs(ctx context.Context, in *CPPProcessInputsRequest, opts ...grpc.CallOption) (*CPPProcessInputsResponse, error)
	Status(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*StatusResponse, error)
	Shutdown(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*StatusResponse, error)
	Capabilities(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*CapabilitiesResponse, error)
}

type cPPDepsScannerClient struct {
	cc grpc.ClientConnInterface
}

func NewCPPDepsScannerClient(cc grpc.ClientConnInterface) CPPDepsScannerClient {
	return &cPPDepsScannerClient{cc}
}

func (c *cPPDepsScannerClient) ProcessInputs(ctx context.Context, in *CPPProcessInputsRequest, opts ...grpc.CallOption) (*CPPProcessInputsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CPPProcessInputsResponse)
	err := c.cc.Invoke(ctx, CPPDepsScanner_ProcessInputs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cPPDepsScannerClient) Status(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, CPPDepsScanner_Status_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cPPDepsScannerClient) Shutdown(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, CPPDepsScanner_Shutdown_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cPPDepsScannerClient) Capabilities(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*CapabilitiesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CapabilitiesResponse)
	err := c.cc.Invoke(ctx, CPPDepsScanner_Capabilities_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CPPDepsScannerServer is the server API for CPPDepsScanner service.
// All implementations should embed UnimplementedCPPDepsScannerServer
// for forward compatibility.
type CPPDepsScannerServer interface {
	ProcessInputs(context.Context, *CPPProcessInputsRequest) (*CPPProcessInputsResponse, error)
	Status(context.Context, *emptypb.Empty) (*StatusResponse, error)
	Shutdown(context.Context, *emptypb.Empty) (*StatusResponse, error)
	Capabilities(context.Context, *emptypb.Empty) (*CapabilitiesResponse, error)
}

// UnimplementedCPPDepsScannerServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCPPDepsScannerServer struct{}

func (UnimplementedCPPDepsScannerServer) ProcessInputs(context.Context, *CPPProcessInputsRequest) (*CPPProcessInputsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProcessInputs not implemented")
}
func (UnimplementedCPPDepsScannerServer) Status(context.Context, *emptypb.Empty) (*StatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Status not implemented")
}
func (UnimplementedCPPDepsScannerServer) Shutdown(context.Context, *emptypb.Empty) (*StatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Shutdown not implemented")
}
func (UnimplementedCPPDepsScannerServer) Capabilities(context.Context, *emptypb.Empty) (*CapabilitiesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Capabilities not implemented")
}
func (UnimplementedCPPDepsScannerServer) testEmbeddedByValue() {}

// UnsafeCPPDepsScannerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CPPDepsScannerServer will
// result in compilation errors.
type UnsafeCPPDepsScannerServer interface {
	mustEmbedUnimplementedCPPDepsScannerServer()
}

func RegisterCPPDepsScannerServer(s grpc.ServiceRegistrar, srv CPPDepsScannerServer) {
	// If the following call pancis, it indicates UnimplementedCPPDepsScannerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CPPDepsScanner_ServiceDesc, srv)
}

func _CPPDepsScanner_ProcessInputs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CPPProcessInputsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CPPDepsScannerServer).ProcessInputs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CPPDepsScanner_ProcessInputs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CPPDepsScannerServer).ProcessInputs(ctx, req.(*CPPProcessInputsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CPPDepsScanner_Status_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CPPDepsScannerServer).Status(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CPPDepsScanner_Status_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CPPDepsScannerServer).Status(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _CPPDepsScanner_Shutdown_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CPPDepsScannerServer).Shutdown(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CPPDepsScanner_Shutdown_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CPPDepsScannerServer).Shutdown(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _CPPDepsScanner_Capabilities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CPPDepsScannerServer).Capabilities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CPPDepsScanner_Capabilities_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CPPDepsScannerServer).Capabilities(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// CPPDepsScanner_ServiceDesc is the grpc.ServiceDesc for CPPDepsScanner service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CPPDepsScanner_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "scandeps.CPPDepsScanner",
	HandlerType: (*CPPDepsScannerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ProcessInputs",
			Handler:    _CPPDepsScanner_ProcessInputs_Handler,
		},
		{
			MethodName: "Status",
			Handler:    _CPPDepsScanner_Status_Handler,
		},
		{
			MethodName: "Shutdown",
			Handler:    _CPPDepsScanner_Shutdown_Handler,
		},
		{
			MethodName: "Capabilities",
			Handler:    _CPPDepsScanner_Capabilities_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/scandeps/cppscandeps.proto",
}
