// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.1
// source: api/scandeps/cppscandeps.proto

package scandeps

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CPPProcessInputsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Command       []string               `protobuf:"bytes,1,rep,name=command,proto3" json:"command,omitempty"`
	Filename      string                 `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`
	Directory     string                 `protobuf:"bytes,3,opt,name=directory,proto3" json:"directory,omitempty"`
	CmdEnv        []string               `protobuf:"bytes,4,rep,name=cmd_env,json=cmdEnv,proto3" json:"cmd_env,omitempty"`
	ExecId        string                 `protobuf:"bytes,5,opt,name=exec_id,json=execId,proto3" json:"exec_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CPPProcessInputsRequest) Reset() {
	*x = CPPProcessInputsRequest{}
	mi := &file_api_scandeps_cppscandeps_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CPPProcessInputsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CPPProcessInputsRequest) ProtoMessage() {}

func (x *CPPProcessInputsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_scandeps_cppscandeps_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CPPProcessInputsRequest.ProtoReflect.Descriptor instead.
func (*CPPProcessInputsRequest) Descriptor() ([]byte, []int) {
	return file_api_scandeps_cppscandeps_proto_rawDescGZIP(), []int{0}
}

func (x *CPPProcessInputsRequest) GetCommand() []string {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *CPPProcessInputsRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *CPPProcessInputsRequest) GetDirectory() string {
	if x != nil {
		return x.Directory
	}
	return ""
}

func (x *CPPProcessInputsRequest) GetCmdEnv() []string {
	if x != nil {
		return x.CmdEnv
	}
	return nil
}

func (x *CPPProcessInputsRequest) GetExecId() string {
	if x != nil {
		return x.ExecId
	}
	return ""
}

type CPPProcessInputsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Dependencies  []string               `protobuf:"bytes,1,rep,name=dependencies,proto3" json:"dependencies,omitempty"`
	UsedCache     bool                   `protobuf:"varint,2,opt,name=used_cache,json=usedCache,proto3" json:"used_cache,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CPPProcessInputsResponse) Reset() {
	*x = CPPProcessInputsResponse{}
	mi := &file_api_scandeps_cppscandeps_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CPPProcessInputsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CPPProcessInputsResponse) ProtoMessage() {}

func (x *CPPProcessInputsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_scandeps_cppscandeps_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CPPProcessInputsResponse.ProtoReflect.Descriptor instead.
func (*CPPProcessInputsResponse) Descriptor() ([]byte, []int) {
	return file_api_scandeps_cppscandeps_proto_rawDescGZIP(), []int{1}
}

func (x *CPPProcessInputsResponse) GetDependencies() []string {
	if x != nil {
		return x.Dependencies
	}
	return nil
}

func (x *CPPProcessInputsResponse) GetUsedCache() bool {
	if x != nil {
		return x.UsedCache
	}
	return false
}

func (x *CPPProcessInputsResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type StatusResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Name                 string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version              string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Uptime               *durationpb.Duration   `protobuf:"bytes,3,opt,name=uptime,proto3" json:"uptime,omitempty"`
	CompletedActions     int32                  `protobuf:"varint,4,opt,name=completed_actions,json=completedActions,proto3" json:"completed_actions,omitempty"`
	RunningActions       int32                  `protobuf:"varint,5,opt,name=running_actions,json=runningActions,proto3" json:"running_actions,omitempty"`
	LongestCurrentAction *durationpb.Duration   `protobuf:"bytes,6,opt,name=longest_current_action,json=longestCurrentAction,proto3" json:"longest_current_action,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_api_scandeps_cppscandeps_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_scandeps_cppscandeps_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_api_scandeps_cppscandeps_proto_rawDescGZIP(), []int{2}
}

func (x *StatusResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *StatusResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *StatusResponse) GetUptime() *durationpb.Duration {
	if x != nil {
		return x.Uptime
	}
	return nil
}

func (x *StatusResponse) GetCompletedActions() int32 {
	if x != nil {
		return x.CompletedActions
	}
	return 0
}

func (x *StatusResponse) GetRunningActions() int32 {
	if x != nil {
		return x.RunningActions
	}
	return 0
}

func (x *StatusResponse) GetLongestCurrentAction() *durationpb.Duration {
	if x != nil {
		return x.LongestCurrentAction
	}
	return nil
}

type CapabilitiesResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Caching            bool                   `protobuf:"varint,1,opt,name=caching,proto3" json:"caching,omitempty"`
	ExpectsResourceDir bool                   `protobuf:"varint,2,opt,name=expects_resource_dir,json=expectsResourceDir,proto3" json:"expects_resource_dir,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *CapabilitiesResponse) Reset() {
	*x = CapabilitiesResponse{}
	mi := &file_api_scandeps_cppscandeps_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CapabilitiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CapabilitiesResponse) ProtoMessage() {}

func (x *CapabilitiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_scandeps_cppscandeps_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CapabilitiesResponse.ProtoReflect.Descriptor instead.
func (*CapabilitiesResponse) Descriptor() ([]byte, []int) {
	return file_api_scandeps_cppscandeps_proto_rawDescGZIP(), []int{3}
}

func (x *CapabilitiesResponse) GetCaching() bool {
	if x != nil {
		return x.Caching
	}
	return false
}

func (x *CapabilitiesResponse) GetExpectsResourceDir() bool {
	if x != nil {
		return x.ExpectsResourceDir
	}
	return false
}

var File_api_scandeps_cppscandeps_proto protoreflect.FileDescriptor

const file_api_scandeps_cppscandeps_proto_rawDesc = "" +
	"\n" +
	"\x1eapi/scandeps/cppscandeps.proto\x12\bscandeps\x1a\x1egoogle/protobuf/duration.proto\x1a\x1bgoogle/protobuf/empty.proto\"\x9f\x01\n" +
	"\x17CPPProcessInputsRequest\x12\x18\n" +
	"\acommand\x18\x01 \x03(\tR\acommand\x12\x1a\n" +
	"\bfilename\x18\x02 \x01(\tR\bfilename\x12\x1c\n" +
	"\tdirectory\x18\x03 \x01(\tR\tdirectory\x12\x17\n" +
	"\acmd_env\x18\x04 \x03(\tR\x06cmdEnv\x12\x17\n" +
	"\aexec_id\x18\x05 \x01(\tR\x06execId\"s\n" +
	"\x18CPPProcessInputsResponse\x12\"\n" +
	"\fdependencies\x18\x01 \x03(\tR\fdependencies\x12\x1d\n" +
	"\n" +
	"used_cache\x18\x02 \x01(\bR\tusedCache\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"\x98\x02\n" +
	"\x0eStatusResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x121\n" +
	"\x06uptime\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\x06uptime\x12+\n" +
	"\x11completed_actions\x18\x04 \x01(\x05R\x10completedActions\x12'\n" +
	"\x0frunning_actions\x18\x05 \x01(\x05R\x0erunningActions\x12O\n" +
	"\x16longest_current_action\x18\x06 \x01(\v2\x19.google.protobuf.DurationR\x14longestCurrentAction\"b\n" +
	"\x14CapabilitiesResponse\x12\x18\n" +
	"\acaching\x18\x01 \x01(\bR\acaching\x120\n" +
	"\x14expects_resource_dir\x18\x02 \x01(\bR\x12expectsResourceDir2\xb2\x02\n" +
	"\x0eCPPDepsScanner\x12X\n" +
	"\rProcessInputs\x12!.scandeps.CPPProcessInputsRequest\x1a\".scandeps.CPPProcessInputsResponse\"\x00\x12<\n" +
	"\x06Status\x12\x16.google.protobuf.Empty\x1a\x18.scandeps.StatusResponse\"\x00\x12>\n" +
	"\bShutdown\x12\x16.google.protobuf.Empty\x1a\x18.scandeps.StatusResponse\"\x00\x12H\n" +
	"\fCapabilities\x12\x16.google.protobuf.Empty\x1a\x1e.scandeps.CapabilitiesResponse\"\x00B-Z+github.com/bazelbuild/reclient/api/scandepsb\x06proto3"

var (
	file_api_scandeps_cppscandeps_proto_rawDescOnce sync.Once
	file_api_scandeps_cppscandeps_proto_rawDescData []byte
)

func file_api_scandeps_cppscandeps_proto_rawDescGZIP() []byte {
	file_api_scandeps_cppscandeps_proto_rawDescOnce.Do(func() {
		file_api_scandeps_cppscandeps_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_scandeps_cppscandeps_proto_rawDesc), len(file_api_scandeps_cppscandeps_proto_rawDesc)))
	})
	return file_api_scandeps_cppscandeps_proto_rawDescData
}

var file_api_scandeps_cppscandeps_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_scandeps_cppscandeps_proto_goTypes = []any{
	(*CPPProcessInputsRequest)(nil),  // 0: scandeps.CPPProcessInputsRequest
	(*CPPProcessInputsResponse)(nil), // 1: scandeps.CPPProcessInputsResponse
	(*StatusResponse)(nil),           // 2: scandeps.StatusResponse
	(*CapabilitiesResponse)(nil),     // 3: scandeps.CapabilitiesResponse
	(*durationpb.Duration)(nil),      // 4: google.protobuf.Duration
	(*emptypb.Empty)(nil),            // 5: google.protobuf.Empty
}
var file_api_scandeps_cppscandeps_proto_depIdxs = []int32{
	4, // 0: scandeps.StatusResponse.uptime:type_name -> google.protobuf.Duration
	4, // 1: scandeps.StatusResponse.longest_current_action:type_name -> google.protobuf.Duration
	0, // 2: scandeps.CPPDepsScanner.ProcessInputs:input_type -> scandeps.CPPProcessInputsRequest
	5, // 3: scandeps.CPPDepsScanner.Status:input_type -> google.protobuf.Empty
	5, // 4: scandeps.CPPDepsScanner.Shutdown:input_type -> google.protobuf.Empty
	5, // 5: scandeps.CPPDepsScanner.Capabilities:input_type -> google.protobuf.Empty
	1, // 6: scandeps.CPPDepsScanner.ProcessInputs:output_type -> scandeps.CPPProcessInputsResponse
	2, // 7: scandeps.CPPDepsScanner.Status:output_type -> scandeps.StatusResponse
	2, // 8: scandeps.CPPDepsScanner.Shutdown:output_type -> scandeps.StatusResponse
	3, // 9: scandeps.CPPDepsScanner.Capabilities:output_type -> scandeps.CapabilitiesResponse
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_scandeps_cppscandeps_proto_init() }
func file_api_scandeps_cppscandeps_proto_init() {
	if File_api_scandeps_cppscandeps_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_scandeps_cppscandeps_proto_rawDesc), len(file_api_scandeps_cppscandeps_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_scandeps_cppscandeps_proto_goTypes,
		DependencyIndexes: file_api_scandeps_cppscandeps_proto_depIdxs,
		MessageInfos:      file_api_scandeps_cppscandeps_proto_msgTypes,
	}.Build()
	File_api_scandeps_cppscandeps_proto = out.File
	file_api_scandeps_cppscandeps_proto_goTypes = nil
	file_api_scandeps_cppscandeps_proto_depIdxs = nil
}
