// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.1
// source: api/proxy/depscache.proto

package proxy

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DepsDatabase struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Files         []*FileInfo            `protobuf:"bytes,1,rep,name=files,proto3" json:"files,omitempty"`
	Deps          []*Deps                `protobuf:"bytes,2,rep,name=deps,proto3" json:"deps,omitempty"`
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DepsDatabase) Reset() {
	*x = DepsDatabase{}
	mi := &file_api_proxy_depscache_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DepsDatabase) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DepsDatabase) ProtoMessage() {}

func (x *DepsDatabase) ProtoReflect() protoreflect.Message {
	mi := &file_api_proxy_depscache_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DepsDatabase.ProtoReflect.Descriptor instead.
func (*DepsDatabase) Descriptor() ([]byte, []int) {
	return file_api_proxy_depscache_proto_rawDescGZIP(), []int{0}
}

func (x *DepsDatabase) GetFiles() []*FileInfo {
	if x != nil {
		return x.Files
	}
	return nil
}

func (x *DepsDatabase) GetDeps() []*Deps {
	if x != nil {
		return x.Deps
	}
	return nil
}

func (x *DepsDatabase) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type FileInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AbsPath       string                 `protobuf:"bytes,1,opt,name=abs_path,json=absPath,proto3" json:"abs_path,omitempty"`
	Digest        string                 `protobuf:"bytes,2,opt,name=digest,proto3" json:"digest,omitempty"`
	Mtime         *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=mtime,proto3" json:"mtime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileInfo) Reset() {
	*x = FileInfo{}
	mi := &file_api_proxy_depscache_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileInfo) ProtoMessage() {}

func (x *FileInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_proxy_depscache_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileInfo.ProtoReflect.Descriptor instead.
func (*FileInfo) Descriptor() ([]byte, []int) {
	return file_api_proxy_depscache_proto_rawDescGZIP(), []int{1}
}

func (x *FileInfo) GetAbsPath() string {
	if x != nil {
		return x.AbsPath
	}
	return ""
}

func (x *FileInfo) GetDigest() string {
	if x != nil {
		return x.Digest
	}
	return ""
}

func (x *FileInfo) GetMtime() *timestamppb.Timestamp {
	if x != nil {
		return x.Mtime
	}
	return nil
}

type Deps struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SrcFile       *FileInfo              `protobuf:"bytes,1,opt,name=src_file,json=srcFile,proto3" json:"src_file,omitempty"`
	CommandDigest string                 `protobuf:"bytes,2,opt,name=command_digest,json=commandDigest,proto3" json:"command_digest,omitempty"`
	LastUsed      *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=last_used,json=lastUsed,proto3" json:"last_used,omitempty"`
	DepIds        []int64                `protobuf:"varint,4,rep,packed,name=dep_ids,json=depIds,proto3" json:"dep_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Deps) Reset() {
	*x = Deps{}
	mi := &file_api_proxy_depscache_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Deps) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Deps) ProtoMessage() {}

func (x *Deps) ProtoReflect() protoreflect.Message {
	mi := &file_api_proxy_depscache_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Deps.ProtoReflect.Descriptor instead.
func (*Deps) Descriptor() ([]byte, []int) {
	return file_api_proxy_depscache_proto_rawDescGZIP(), []int{2}
}

func (x *Deps) GetSrcFile() *FileInfo {
	if x != nil {
		return x.SrcFile
	}
	return nil
}

func (x *Deps) GetCommandDigest() string {
	if x != nil {
		return x.CommandDigest
	}
	return ""
}

func (x *Deps) GetLastUsed() *timestamppb.Timestamp {
	if x != nil {
		return x.LastUsed
	}
	return nil
}

func (x *Deps) GetDepIds() []int64 {
	if x != nil {
		return x.DepIds
	}
	return nil
}

var File_api_proxy_depscache_proto protoreflect.FileDescriptor

const file_api_proxy_depscache_proto_rawDesc = "" +
	"\n" +
	"\x19api/proxy/depscache.proto\x12\x05proxy\x1a\x1fgoogle/protobuf/timestamp.proto\"p\n" +
	"\fDepsDatabase\x12%\n" +
	"\x05files\x18\x01 \x03(\v2\x0f.proxy.FileInfoR\x05files\x12\x1f\n" +
	"\x04deps\x18\x02 \x03(\v2\v.proxy.DepsR\x04deps\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\"o\n" +
	"\bFileInfo\x12\x19\n" +
	"\babs_path\x18\x01 \x01(\tR\aabsPath\x12\x16\n" +
	"\x06digest\x18\x02 \x01(\tR\x06digest\x120\n" +
	"\x05mtime\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x05mtime\"\xab\x01\n" +
	"\x04Deps\x12*\n" +
	"\bsrc_file\x18\x01 \x01(\v2\x0f.proxy.FileInfoR\asrcFile\x12%\n" +
	"\x0ecommand_digest\x18\x02 \x01(\tR\rcommandDigest\x127\n" +
	"\tlast_used\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\blastUsed\x12\x17\n" +
	"\adep_ids\x18\x04 \x03(\x03R\x06depIdsB*Z(github.com/bazelbuild/reclient/api/proxyb\x06proto3"

var (
	file_api_proxy_depscache_proto_rawDescOnce sync.Once
	file_api_proxy_depscache_proto_rawDescData []byte
)

func file_api_proxy_depscache_proto_rawDescGZIP() []byte {
	file_api_proxy_depscache_proto_rawDescOnce.Do(func() {
		file_api_proxy_depscache_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proxy_depscache_proto_rawDesc), len(file_api_proxy_depscache_proto_rawDesc)))
	})
	return file_api_proxy_depscache_proto_rawDescData
}

var file_api_proxy_depscache_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_api_proxy_depscache_proto_goTypes = []any{
	(*DepsDatabase)(nil),          // 0: proxy.DepsDatabase
	(*FileInfo)(nil),              // 1: proxy.FileInfo
	(*Deps)(nil),                  // 2: proxy.Deps
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
}
var file_api_proxy_depscache_proto_depIdxs = []int32{
	1, // 0: proxy.DepsDatabase.files:type_name -> proxy.FileInfo
	2, // 1: proxy.DepsDatabase.deps:type_name -> proxy.Deps
	3, // 2: proxy.FileInfo.mtime:type_name -> google.protobuf.Timestamp
	1, // 3: proxy.Deps.src_file:type_name -> proxy.FileInfo
	3, // 4: proxy.Deps.last_used:type_name -> google.protobuf.Timestamp
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_api_proxy_depscache_proto_init() }
func file_api_proxy_depscache_proto_init() {
	if File_api_proxy_depscache_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proxy_depscache_proto_rawDesc), len(file_api_proxy_depscache_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_proxy_depscache_proto_goTypes,
		DependencyIndexes: file_api_proxy_depscache_proto_depIdxs,
		MessageInfos:      file_api_proxy_depscache_proto_msgTypes,
	}.Build()
	File_api_proxy_depscache_proto = out.File
	file_api_proxy_depscache_proto_goTypes = nil
	file_api_proxy_depscache_proto_depIdxs = nil
}
