// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.1
// source: api/proxy/mismatch_ignore_rule.proto

package proxy

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MismatchIgnoreConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rules         []*Rule                `protobuf:"bytes,1,rep,name=rules,proto3" json:"rules,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MismatchIgnoreConfig) Reset() {
	*x = MismatchIgnoreConfig{}
	mi := &file_api_proxy_mismatch_ignore_rule_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MismatchIgnoreConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MismatchIgnoreConfig) ProtoMessage() {}

func (x *MismatchIgnoreConfig) ProtoReflect() protoreflect.Message {
	mi := &file_api_proxy_mismatch_ignore_rule_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MismatchIgnoreConfig.ProtoReflect.Descriptor instead.
func (*MismatchIgnoreConfig) Descriptor() ([]byte, []int) {
	return file_api_proxy_mismatch_ignore_rule_proto_rawDescGZIP(), []int{0}
}

func (x *MismatchIgnoreConfig) GetRules() []*Rule {
	if x != nil {
		return x.Rules
	}
	return nil
}

type Rule struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to RuleSpec:
	//
	//	*Rule_OutputFilePathRuleSpec
	RuleSpec      isRule_RuleSpec `protobuf_oneof:"rule_spec"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Rule) Reset() {
	*x = Rule{}
	mi := &file_api_proxy_mismatch_ignore_rule_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Rule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rule) ProtoMessage() {}

func (x *Rule) ProtoReflect() protoreflect.Message {
	mi := &file_api_proxy_mismatch_ignore_rule_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rule.ProtoReflect.Descriptor instead.
func (*Rule) Descriptor() ([]byte, []int) {
	return file_api_proxy_mismatch_ignore_rule_proto_rawDescGZIP(), []int{1}
}

func (x *Rule) GetRuleSpec() isRule_RuleSpec {
	if x != nil {
		return x.RuleSpec
	}
	return nil
}

func (x *Rule) GetOutputFilePathRuleSpec() *OutputFilePathRuleSpec {
	if x != nil {
		if x, ok := x.RuleSpec.(*Rule_OutputFilePathRuleSpec); ok {
			return x.OutputFilePathRuleSpec
		}
	}
	return nil
}

type isRule_RuleSpec interface {
	isRule_RuleSpec()
}

type Rule_OutputFilePathRuleSpec struct {
	OutputFilePathRuleSpec *OutputFilePathRuleSpec `protobuf:"bytes,1,opt,name=output_file_path_rule_spec,json=outputFilePathRuleSpec,proto3,oneof"`
}

func (*Rule_OutputFilePathRuleSpec) isRule_RuleSpec() {}

type OutputFilePathRuleSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PathPattern   *RegexPattern          `protobuf:"bytes,1,opt,name=path_pattern,json=pathPattern,proto3" json:"path_pattern,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OutputFilePathRuleSpec) Reset() {
	*x = OutputFilePathRuleSpec{}
	mi := &file_api_proxy_mismatch_ignore_rule_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OutputFilePathRuleSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutputFilePathRuleSpec) ProtoMessage() {}

func (x *OutputFilePathRuleSpec) ProtoReflect() protoreflect.Message {
	mi := &file_api_proxy_mismatch_ignore_rule_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutputFilePathRuleSpec.ProtoReflect.Descriptor instead.
func (*OutputFilePathRuleSpec) Descriptor() ([]byte, []int) {
	return file_api_proxy_mismatch_ignore_rule_proto_rawDescGZIP(), []int{2}
}

func (x *OutputFilePathRuleSpec) GetPathPattern() *RegexPattern {
	if x != nil {
		return x.PathPattern
	}
	return nil
}

type RegexPattern struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Expression    string                 `protobuf:"bytes,1,opt,name=expression,proto3" json:"expression,omitempty"`
	Inverted      bool                   `protobuf:"varint,2,opt,name=inverted,proto3" json:"inverted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegexPattern) Reset() {
	*x = RegexPattern{}
	mi := &file_api_proxy_mismatch_ignore_rule_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegexPattern) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegexPattern) ProtoMessage() {}

func (x *RegexPattern) ProtoReflect() protoreflect.Message {
	mi := &file_api_proxy_mismatch_ignore_rule_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegexPattern.ProtoReflect.Descriptor instead.
func (*RegexPattern) Descriptor() ([]byte, []int) {
	return file_api_proxy_mismatch_ignore_rule_proto_rawDescGZIP(), []int{3}
}

func (x *RegexPattern) GetExpression() string {
	if x != nil {
		return x.Expression
	}
	return ""
}

func (x *RegexPattern) GetInverted() bool {
	if x != nil {
		return x.Inverted
	}
	return false
}

var File_api_proxy_mismatch_ignore_rule_proto protoreflect.FileDescriptor

const file_api_proxy_mismatch_ignore_rule_proto_rawDesc = "" +
	"\n" +
	"$api/proxy/mismatch_ignore_rule.proto\x12\x05proxy\"9\n" +
	"\x14MismatchIgnoreConfig\x12!\n" +
	"\x05rules\x18\x01 \x03(\v2\v.proxy.RuleR\x05rules\"p\n" +
	"\x04Rule\x12[\n" +
	"\x1aoutput_file_path_rule_spec\x18\x01 \x01(\v2\x1d.proxy.OutputFilePathRuleSpecH\x00R\x16outputFilePathRuleSpecB\v\n" +
	"\trule_spec\"P\n" +
	"\x16OutputFilePathRuleSpec\x126\n" +
	"\fpath_pattern\x18\x01 \x01(\v2\x13.proxy.RegexPatternR\vpathPattern\"J\n" +
	"\fRegexPattern\x12\x1e\n" +
	"\n" +
	"expression\x18\x01 \x01(\tR\n" +
	"expression\x12\x1a\n" +
	"\binverted\x18\x02 \x01(\bR\binvertedB*Z(github.com/bazelbuild/reclient/api/proxyb\x06proto3"

var (
	file_api_proxy_mismatch_ignore_rule_proto_rawDescOnce sync.Once
	file_api_proxy_mismatch_ignore_rule_proto_rawDescData []byte
)

func file_api_proxy_mismatch_ignore_rule_proto_rawDescGZIP() []byte {
	file_api_proxy_mismatch_ignore_rule_proto_rawDescOnce.Do(func() {
		file_api_proxy_mismatch_ignore_rule_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proxy_mismatch_ignore_rule_proto_rawDesc), len(file_api_proxy_mismatch_ignore_rule_proto_rawDesc)))
	})
	return file_api_proxy_mismatch_ignore_rule_proto_rawDescData
}

var file_api_proxy_mismatch_ignore_rule_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_proxy_mismatch_ignore_rule_proto_goTypes = []any{
	(*MismatchIgnoreConfig)(nil),   // 0: proxy.MismatchIgnoreConfig
	(*Rule)(nil),                   // 1: proxy.Rule
	(*OutputFilePathRuleSpec)(nil), // 2: proxy.OutputFilePathRuleSpec
	(*RegexPattern)(nil),           // 3: proxy.RegexPattern
}
var file_api_proxy_mismatch_ignore_rule_proto_depIdxs = []int32{
	1, // 0: proxy.MismatchIgnoreConfig.rules:type_name -> proxy.Rule
	2, // 1: proxy.Rule.output_file_path_rule_spec:type_name -> proxy.OutputFilePathRuleSpec
	3, // 2: proxy.OutputFilePathRuleSpec.path_pattern:type_name -> proxy.RegexPattern
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_api_proxy_mismatch_ignore_rule_proto_init() }
func file_api_proxy_mismatch_ignore_rule_proto_init() {
	if File_api_proxy_mismatch_ignore_rule_proto != nil {
		return
	}
	file_api_proxy_mismatch_ignore_rule_proto_msgTypes[1].OneofWrappers = []any{
		(*Rule_OutputFilePathRuleSpec)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proxy_mismatch_ignore_rule_proto_rawDesc), len(file_api_proxy_mismatch_ignore_rule_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_proxy_mismatch_ignore_rule_proto_goTypes,
		DependencyIndexes: file_api_proxy_mismatch_ignore_rule_proto_depIdxs,
		MessageInfos:      file_api_proxy_mismatch_ignore_rule_proto_msgTypes,
	}.Build()
	File_api_proxy_mismatch_ignore_rule_proto = out.File
	file_api_proxy_mismatch_ignore_rule_proto_goTypes = nil
	file_api_proxy_mismatch_ignore_rule_proto_depIdxs = nil
}
