// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.1
// source: api/proxy/proxy.proto

package proxy

import (
	log "github.com/bazelbuild/reclient/api/log"
	stats "github.com/bazelbuild/reclient/api/stats"
	command "github.com/bazelbuild/remote-apis-sdks/go/api/command"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExecutionStrategy_Value int32

const (
	ExecutionStrategy_UNSPECIFIED           ExecutionStrategy_Value = 0
	ExecutionStrategy_LOCAL                 ExecutionStrategy_Value = 1
	ExecutionStrategy_REMOTE                ExecutionStrategy_Value = 2
	ExecutionStrategy_REMOTE_LOCAL_FALLBACK ExecutionStrategy_Value = 3
	ExecutionStrategy_RACING                ExecutionStrategy_Value = 4
)

// Enum value maps for ExecutionStrategy_Value.
var (
	ExecutionStrategy_Value_name = map[int32]string{
		0: "UNSPECIFIED",
		1: "LOCAL",
		2: "REMOTE",
		3: "REMOTE_LOCAL_FALLBACK",
		4: "RACING",
	}
	ExecutionStrategy_Value_value = map[string]int32{
		"UNSPECIFIED":           0,
		"LOCAL":                 1,
		"REMOTE":                2,
		"REMOTE_LOCAL_FALLBACK": 3,
		"RACING":                4,
	}
)

func (x ExecutionStrategy_Value) Enum() *ExecutionStrategy_Value {
	p := new(ExecutionStrategy_Value)
	*p = x
	return p
}

func (x ExecutionStrategy_Value) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ExecutionStrategy_Value) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proxy_proxy_proto_enumTypes[0].Descriptor()
}

func (ExecutionStrategy_Value) Type() protoreflect.EnumType {
	return &file_api_proxy_proxy_proto_enumTypes[0]
}

func (x ExecutionStrategy_Value) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ExecutionStrategy_Value.Descriptor instead.
func (ExecutionStrategy_Value) EnumDescriptor() ([]byte, []int) {
	return file_api_proxy_proxy_proto_rawDescGZIP(), []int{12, 0}
}

type LocalExecutionOptions_LocalExecutionPlatform int32

const (
	LocalExecutionOptions_UNSPECIFIED LocalExecutionOptions_LocalExecutionPlatform = 0
	LocalExecutionOptions_DOCKER      LocalExecutionOptions_LocalExecutionPlatform = 1
)

// Enum value maps for LocalExecutionOptions_LocalExecutionPlatform.
var (
	LocalExecutionOptions_LocalExecutionPlatform_name = map[int32]string{
		0: "UNSPECIFIED",
		1: "DOCKER",
	}
	LocalExecutionOptions_LocalExecutionPlatform_value = map[string]int32{
		"UNSPECIFIED": 0,
		"DOCKER":      1,
	}
)

func (x LocalExecutionOptions_LocalExecutionPlatform) Enum() *LocalExecutionOptions_LocalExecutionPlatform {
	p := new(LocalExecutionOptions_LocalExecutionPlatform)
	*p = x
	return p
}

func (x LocalExecutionOptions_LocalExecutionPlatform) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LocalExecutionOptions_LocalExecutionPlatform) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proxy_proxy_proto_enumTypes[1].Descriptor()
}

func (LocalExecutionOptions_LocalExecutionPlatform) Type() protoreflect.EnumType {
	return &file_api_proxy_proxy_proto_enumTypes[1]
}

func (x LocalExecutionOptions_LocalExecutionPlatform) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LocalExecutionOptions_LocalExecutionPlatform.Descriptor instead.
func (LocalExecutionOptions_LocalExecutionPlatform) EnumDescriptor() ([]byte, []int) {
	return file_api_proxy_proxy_proto_rawDescGZIP(), []int{13, 0}
}

type ShutdownRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShutdownRequest) Reset() {
	*x = ShutdownRequest{}
	mi := &file_api_proxy_proxy_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShutdownRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownRequest) ProtoMessage() {}

func (x *ShutdownRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proxy_proxy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShutdownRequest.ProtoReflect.Descriptor instead.
func (*ShutdownRequest) Descriptor() ([]byte, []int) {
	return file_api_proxy_proxy_proto_rawDescGZIP(), []int{0}
}

type ShutdownResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stats         *stats.Stats           `protobuf:"bytes,1,opt,name=stats,proto3" json:"stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShutdownResponse) Reset() {
	*x = ShutdownResponse{}
	mi := &file_api_proxy_proxy_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShutdownResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownResponse) ProtoMessage() {}

func (x *ShutdownResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proxy_proxy_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShutdownResponse.ProtoReflect.Descriptor instead.
func (*ShutdownResponse) Descriptor() ([]byte, []int) {
	return file_api_proxy_proxy_proto_rawDescGZIP(), []int{1}
}

func (x *ShutdownResponse) GetStats() *stats.Stats {
	if x != nil {
		return x.Stats
	}
	return nil
}

type GetStatusSummaryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatusSummaryRequest) Reset() {
	*x = GetStatusSummaryRequest{}
	mi := &file_api_proxy_proxy_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusSummaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusSummaryRequest) ProtoMessage() {}

func (x *GetStatusSummaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proxy_proxy_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusSummaryRequest.ProtoReflect.Descriptor instead.
func (*GetStatusSummaryRequest) Descriptor() ([]byte, []int) {
	return file_api_proxy_proxy_proto_rawDescGZIP(), []int{2}
}

type GetStatusSummaryResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	CompletedActionStats map[string]int32       `protobuf:"bytes,1,rep,name=completed_action_stats,json=completedActionStats,proto3" json:"completed_action_stats,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	RunningActions       int32                  `protobuf:"varint,2,opt,name=running_actions,json=runningActions,proto3" json:"running_actions,omitempty"`
	Qps                  int32                  `protobuf:"varint,3,opt,name=qps,proto3" json:"qps,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *GetStatusSummaryResponse) Reset() {
	*x = GetStatusSummaryResponse{}
	mi := &file_api_proxy_proxy_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusSummaryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusSummaryResponse) ProtoMessage() {}

func (x *GetStatusSummaryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proxy_proxy_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusSummaryResponse.ProtoReflect.Descriptor instead.
func (*GetStatusSummaryResponse) Descriptor() ([]byte, []int) {
	return file_api_proxy_proxy_proto_rawDescGZIP(), []int{3}
}

func (x *GetStatusSummaryResponse) GetCompletedActionStats() map[string]int32 {
	if x != nil {
		return x.CompletedActionStats
	}
	return nil
}

func (x *GetStatusSummaryResponse) GetRunningActions() int32 {
	if x != nil {
		return x.RunningActions
	}
	return 0
}

func (x *GetStatusSummaryResponse) GetQps() int32 {
	if x != nil {
		return x.Qps
	}
	return 0
}

type GetRecordsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRecordsRequest) Reset() {
	*x = GetRecordsRequest{}
	mi := &file_api_proxy_proxy_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRecordsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRecordsRequest) ProtoMessage() {}

func (x *GetRecordsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proxy_proxy_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRecordsRequest.ProtoReflect.Descriptor instead.
func (*GetRecordsRequest) Descriptor() ([]byte, []int) {
	return file_api_proxy_proxy_proto_rawDescGZIP(), []int{4}
}

type GetRecordsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Records       []*log.LogRecord       `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRecordsResponse) Reset() {
	*x = GetRecordsResponse{}
	mi := &file_api_proxy_proxy_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRecordsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRecordsResponse) ProtoMessage() {}

func (x *GetRecordsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proxy_proxy_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRecordsResponse.ProtoReflect.Descriptor instead.
func (*GetRecordsResponse) Descriptor() ([]byte, []int) {
	return file_api_proxy_proxy_proto_rawDescGZIP(), []int{5}
}

func (x *GetRecordsResponse) GetRecords() []*log.LogRecord {
	if x != nil {
		return x.Records
	}
	return nil
}

type AddProxyEventsRequest struct {
	state         protoimpl.MessageState           `protogen:"open.v1"`
	EventTimes    map[string]*command.TimeInterval `protobuf:"bytes,1,rep,name=event_times,json=eventTimes,proto3" json:"event_times,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddProxyEventsRequest) Reset() {
	*x = AddProxyEventsRequest{}
	mi := &file_api_proxy_proxy_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddProxyEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddProxyEventsRequest) ProtoMessage() {}

func (x *AddProxyEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proxy_proxy_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddProxyEventsRequest.ProtoReflect.Descriptor instead.
func (*AddProxyEventsRequest) Descriptor() ([]byte, []int) {
	return file_api_proxy_proxy_proto_rawDescGZIP(), []int{6}
}

func (x *AddProxyEventsRequest) GetEventTimes() map[string]*command.TimeInterval {
	if x != nil {
		return x.EventTimes
	}
	return nil
}

type AddProxyEventsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddProxyEventsResponse) Reset() {
	*x = AddProxyEventsResponse{}
	mi := &file_api_proxy_proxy_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddProxyEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddProxyEventsResponse) ProtoMessage() {}

func (x *AddProxyEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proxy_proxy_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddProxyEventsResponse.ProtoReflect.Descriptor instead.
func (*AddProxyEventsResponse) Descriptor() ([]byte, []int) {
	return file_api_proxy_proxy_proto_rawDescGZIP(), []int{7}
}

type RunRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Command          *command.Command       `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	Labels           map[string]string      `protobuf:"bytes,2,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ExecutionOptions *ProxyExecutionOptions `protobuf:"bytes,3,opt,name=execution_options,json=executionOptions,proto3" json:"execution_options,omitempty"`
	Metadata         *Metadata              `protobuf:"bytes,4,opt,name=metadata,proto3" json:"metadata,omitempty"`
	ToolchainInputs  []string               `protobuf:"bytes,5,rep,name=toolchain_inputs,json=toolchainInputs,proto3" json:"toolchain_inputs,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RunRequest) Reset() {
	*x = RunRequest{}
	mi := &file_api_proxy_proxy_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunRequest) ProtoMessage() {}

func (x *RunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proxy_proxy_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunRequest.ProtoReflect.Descriptor instead.
func (*RunRequest) Descriptor() ([]byte, []int) {
	return file_api_proxy_proxy_proto_rawDescGZIP(), []int{8}
}

func (x *RunRequest) GetCommand() *command.Command {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *RunRequest) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *RunRequest) GetExecutionOptions() *ProxyExecutionOptions {
	if x != nil {
		return x.ExecutionOptions
	}
	return nil
}

func (x *RunRequest) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *RunRequest) GetToolchainInputs() []string {
	if x != nil {
		return x.ToolchainInputs
	}
	return nil
}

type RunResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Stdout             []byte                 `protobuf:"bytes,1,opt,name=stdout,proto3" json:"stdout,omitempty"`
	Stderr             []byte                 `protobuf:"bytes,2,opt,name=stderr,proto3" json:"stderr,omitempty"`
	Result             *command.CommandResult `protobuf:"bytes,3,opt,name=result,proto3" json:"result,omitempty"`
	ExecutionId        string                 `protobuf:"bytes,4,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	ActionLog          *log.LogRecord         `protobuf:"bytes,5,opt,name=action_log,json=actionLog,proto3" json:"action_log,omitempty"`
	RemoteFallbackInfo *RemoteFallbackInfo    `protobuf:"bytes,6,opt,name=remote_fallback_info,json=remoteFallbackInfo,proto3" json:"remote_fallback_info,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *RunResponse) Reset() {
	*x = RunResponse{}
	mi := &file_api_proxy_proxy_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunResponse) ProtoMessage() {}

func (x *RunResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proxy_proxy_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunResponse.ProtoReflect.Descriptor instead.
func (*RunResponse) Descriptor() ([]byte, []int) {
	return file_api_proxy_proxy_proto_rawDescGZIP(), []int{9}
}

func (x *RunResponse) GetStdout() []byte {
	if x != nil {
		return x.Stdout
	}
	return nil
}

func (x *RunResponse) GetStderr() []byte {
	if x != nil {
		return x.Stderr
	}
	return nil
}

func (x *RunResponse) GetResult() *command.CommandResult {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *RunResponse) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

func (x *RunResponse) GetActionLog() *log.LogRecord {
	if x != nil {
		return x.ActionLog
	}
	return nil
}

func (x *RunResponse) GetRemoteFallbackInfo() *RemoteFallbackInfo {
	if x != nil {
		return x.RemoteFallbackInfo
	}
	return nil
}

type RemoteFallbackInfo struct {
	state         protoimpl.MessageState            `protogen:"open.v1"`
	ExitCode      int32                             `protobuf:"varint,1,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	Stdout        []byte                            `protobuf:"bytes,2,opt,name=stdout,proto3" json:"stdout,omitempty"`
	Stderr        []byte                            `protobuf:"bytes,3,opt,name=stderr,proto3" json:"stderr,omitempty"`
	ResultStatus  command.CommandResultStatus_Value `protobuf:"varint,4,opt,name=result_status,json=resultStatus,proto3,enum=cmd.CommandResultStatus_Value" json:"result_status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoteFallbackInfo) Reset() {
	*x = RemoteFallbackInfo{}
	mi := &file_api_proxy_proxy_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoteFallbackInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoteFallbackInfo) ProtoMessage() {}

func (x *RemoteFallbackInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_proxy_proxy_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoteFallbackInfo.ProtoReflect.Descriptor instead.
func (*RemoteFallbackInfo) Descriptor() ([]byte, []int) {
	return file_api_proxy_proxy_proto_rawDescGZIP(), []int{10}
}

func (x *RemoteFallbackInfo) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *RemoteFallbackInfo) GetStdout() []byte {
	if x != nil {
		return x.Stdout
	}
	return nil
}

func (x *RemoteFallbackInfo) GetStderr() []byte {
	if x != nil {
		return x.Stderr
	}
	return nil
}

func (x *RemoteFallbackInfo) GetResultStatus() command.CommandResultStatus_Value {
	if x != nil {
		return x.ResultStatus
	}
	return command.CommandResultStatus_Value(0)
}

type ProxyExecutionOptions struct {
	state                  protoimpl.MessageState  `protogen:"open.v1"`
	ExecutionStrategy      ExecutionStrategy_Value `protobuf:"varint,1,opt,name=execution_strategy,json=executionStrategy,proto3,enum=proxy.ExecutionStrategy_Value" json:"execution_strategy,omitempty"`
	RemoteExecutionOptions *RemoteExecutionOptions `protobuf:"bytes,2,opt,name=remote_execution_options,json=remoteExecutionOptions,proto3" json:"remote_execution_options,omitempty"`
	LocalExecutionOptions  *LocalExecutionOptions  `protobuf:"bytes,3,opt,name=local_execution_options,json=localExecutionOptions,proto3" json:"local_execution_options,omitempty"`
	CompareWithLocal       bool                    `protobuf:"varint,4,opt,name=compare_with_local,json=compareWithLocal,proto3" json:"compare_with_local,omitempty"`
	NumRetriesIfMismatched int32                   `protobuf:"varint,5,opt,name=num_retries_if_mismatched,json=numRetriesIfMismatched,proto3" json:"num_retries_if_mismatched,omitempty"`
	NumLocalReruns         int32                   `protobuf:"varint,6,opt,name=num_local_reruns,json=numLocalReruns,proto3" json:"num_local_reruns,omitempty"`
	NumRemoteReruns        int32                   `protobuf:"varint,7,opt,name=num_remote_reruns,json=numRemoteReruns,proto3" json:"num_remote_reruns,omitempty"`
	LogEnvironment         bool                    `protobuf:"varint,8,opt,name=log_environment,json=logEnvironment,proto3" json:"log_environment,omitempty"`
	IncludeActionLog       bool                    `protobuf:"varint,9,opt,name=include_action_log,json=includeActionLog,proto3" json:"include_action_log,omitempty"`
	ReclientTimeout        int32                   `protobuf:"varint,10,opt,name=reclient_timeout,json=reclientTimeout,proto3" json:"reclient_timeout,omitempty"`
	EnableAtomicDownloads  bool                    `protobuf:"varint,11,opt,name=enable_atomic_downloads,json=enableAtomicDownloads,proto3" json:"enable_atomic_downloads,omitempty"`
	DownloadRegex          string                  `protobuf:"bytes,12,opt,name=download_regex,json=downloadRegex,proto3" json:"download_regex,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ProxyExecutionOptions) Reset() {
	*x = ProxyExecutionOptions{}
	mi := &file_api_proxy_proxy_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProxyExecutionOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProxyExecutionOptions) ProtoMessage() {}

func (x *ProxyExecutionOptions) ProtoReflect() protoreflect.Message {
	mi := &file_api_proxy_proxy_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProxyExecutionOptions.ProtoReflect.Descriptor instead.
func (*ProxyExecutionOptions) Descriptor() ([]byte, []int) {
	return file_api_proxy_proxy_proto_rawDescGZIP(), []int{11}
}

func (x *ProxyExecutionOptions) GetExecutionStrategy() ExecutionStrategy_Value {
	if x != nil {
		return x.ExecutionStrategy
	}
	return ExecutionStrategy_UNSPECIFIED
}

func (x *ProxyExecutionOptions) GetRemoteExecutionOptions() *RemoteExecutionOptions {
	if x != nil {
		return x.RemoteExecutionOptions
	}
	return nil
}

func (x *ProxyExecutionOptions) GetLocalExecutionOptions() *LocalExecutionOptions {
	if x != nil {
		return x.LocalExecutionOptions
	}
	return nil
}

func (x *ProxyExecutionOptions) GetCompareWithLocal() bool {
	if x != nil {
		return x.CompareWithLocal
	}
	return false
}

func (x *ProxyExecutionOptions) GetNumRetriesIfMismatched() int32 {
	if x != nil {
		return x.NumRetriesIfMismatched
	}
	return 0
}

func (x *ProxyExecutionOptions) GetNumLocalReruns() int32 {
	if x != nil {
		return x.NumLocalReruns
	}
	return 0
}

func (x *ProxyExecutionOptions) GetNumRemoteReruns() int32 {
	if x != nil {
		return x.NumRemoteReruns
	}
	return 0
}

func (x *ProxyExecutionOptions) GetLogEnvironment() bool {
	if x != nil {
		return x.LogEnvironment
	}
	return false
}

func (x *ProxyExecutionOptions) GetIncludeActionLog() bool {
	if x != nil {
		return x.IncludeActionLog
	}
	return false
}

func (x *ProxyExecutionOptions) GetReclientTimeout() int32 {
	if x != nil {
		return x.ReclientTimeout
	}
	return 0
}

func (x *ProxyExecutionOptions) GetEnableAtomicDownloads() bool {
	if x != nil {
		return x.EnableAtomicDownloads
	}
	return false
}

func (x *ProxyExecutionOptions) GetDownloadRegex() string {
	if x != nil {
		return x.DownloadRegex
	}
	return ""
}

type ExecutionStrategy struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecutionStrategy) Reset() {
	*x = ExecutionStrategy{}
	mi := &file_api_proxy_proxy_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutionStrategy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutionStrategy) ProtoMessage() {}

func (x *ExecutionStrategy) ProtoReflect() protoreflect.Message {
	mi := &file_api_proxy_proxy_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutionStrategy.ProtoReflect.Descriptor instead.
func (*ExecutionStrategy) Descriptor() ([]byte, []int) {
	return file_api_proxy_proxy_proto_rawDescGZIP(), []int{12}
}

type LocalExecutionOptions struct {
	state         protoimpl.MessageState                       `protogen:"open.v1"`
	Platform      LocalExecutionOptions_LocalExecutionPlatform `protobuf:"varint,1,opt,name=platform,proto3,enum=proxy.LocalExecutionOptions_LocalExecutionPlatform" json:"platform,omitempty"`
	DoNotCache    bool                                         `protobuf:"varint,2,opt,name=do_not_cache,json=doNotCache,proto3" json:"do_not_cache,omitempty"`
	AcceptCached  bool                                         `protobuf:"varint,3,opt,name=accept_cached,json=acceptCached,proto3" json:"accept_cached,omitempty"`
	Wrapper       string                                       `protobuf:"bytes,4,opt,name=wrapper,proto3" json:"wrapper,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LocalExecutionOptions) Reset() {
	*x = LocalExecutionOptions{}
	mi := &file_api_proxy_proxy_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocalExecutionOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocalExecutionOptions) ProtoMessage() {}

func (x *LocalExecutionOptions) ProtoReflect() protoreflect.Message {
	mi := &file_api_proxy_proxy_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocalExecutionOptions.ProtoReflect.Descriptor instead.
func (*LocalExecutionOptions) Descriptor() ([]byte, []int) {
	return file_api_proxy_proxy_proto_rawDescGZIP(), []int{13}
}

func (x *LocalExecutionOptions) GetPlatform() LocalExecutionOptions_LocalExecutionPlatform {
	if x != nil {
		return x.Platform
	}
	return LocalExecutionOptions_UNSPECIFIED
}

func (x *LocalExecutionOptions) GetDoNotCache() bool {
	if x != nil {
		return x.DoNotCache
	}
	return false
}

func (x *LocalExecutionOptions) GetAcceptCached() bool {
	if x != nil {
		return x.AcceptCached
	}
	return false
}

func (x *LocalExecutionOptions) GetWrapper() string {
	if x != nil {
		return x.Wrapper
	}
	return ""
}

type RemoteExecutionOptions struct {
	state                        protoimpl.MessageState `protogen:"open.v1"`
	AcceptCached                 bool                   `protobuf:"varint,1,opt,name=accept_cached,json=acceptCached,proto3" json:"accept_cached,omitempty"`
	DoNotCache                   bool                   `protobuf:"varint,2,opt,name=do_not_cache,json=doNotCache,proto3" json:"do_not_cache,omitempty"`
	DownloadOutputs              bool                   `protobuf:"varint,3,opt,name=download_outputs,json=downloadOutputs,proto3" json:"download_outputs,omitempty"`
	Wrapper                      string                 `protobuf:"bytes,5,opt,name=wrapper,proto3" json:"wrapper,omitempty"`
	CanonicalizeWorkingDir       bool                   `protobuf:"varint,6,opt,name=canonicalize_working_dir,json=canonicalizeWorkingDir,proto3" json:"canonicalize_working_dir,omitempty"`
	PreserveUnchangedOutputMtime bool                   `protobuf:"varint,7,opt,name=preserve_unchanged_output_mtime,json=preserveUnchangedOutputMtime,proto3" json:"preserve_unchanged_output_mtime,omitempty"`
	unknownFields                protoimpl.UnknownFields
	sizeCache                    protoimpl.SizeCache
}

func (x *RemoteExecutionOptions) Reset() {
	*x = RemoteExecutionOptions{}
	mi := &file_api_proxy_proxy_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoteExecutionOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoteExecutionOptions) ProtoMessage() {}

func (x *RemoteExecutionOptions) ProtoReflect() protoreflect.Message {
	mi := &file_api_proxy_proxy_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoteExecutionOptions.ProtoReflect.Descriptor instead.
func (*RemoteExecutionOptions) Descriptor() ([]byte, []int) {
	return file_api_proxy_proxy_proto_rawDescGZIP(), []int{14}
}

func (x *RemoteExecutionOptions) GetAcceptCached() bool {
	if x != nil {
		return x.AcceptCached
	}
	return false
}

func (x *RemoteExecutionOptions) GetDoNotCache() bool {
	if x != nil {
		return x.DoNotCache
	}
	return false
}

func (x *RemoteExecutionOptions) GetDownloadOutputs() bool {
	if x != nil {
		return x.DownloadOutputs
	}
	return false
}

func (x *RemoteExecutionOptions) GetWrapper() string {
	if x != nil {
		return x.Wrapper
	}
	return ""
}

func (x *RemoteExecutionOptions) GetCanonicalizeWorkingDir() bool {
	if x != nil {
		return x.CanonicalizeWorkingDir
	}
	return false
}

func (x *RemoteExecutionOptions) GetPreserveUnchangedOutputMtime() bool {
	if x != nil {
		return x.PreserveUnchangedOutputMtime
	}
	return false
}

type Metadata struct {
	state         protoimpl.MessageState           `protogen:"open.v1"`
	EventTimes    map[string]*command.TimeInterval `protobuf:"bytes,1,rep,name=event_times,json=eventTimes,proto3" json:"event_times,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Environment   []string                         `protobuf:"bytes,2,rep,name=environment,proto3" json:"environment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Metadata) Reset() {
	*x = Metadata{}
	mi := &file_api_proxy_proxy_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metadata) ProtoMessage() {}

func (x *Metadata) ProtoReflect() protoreflect.Message {
	mi := &file_api_proxy_proxy_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metadata.ProtoReflect.Descriptor instead.
func (*Metadata) Descriptor() ([]byte, []int) {
	return file_api_proxy_proxy_proto_rawDescGZIP(), []int{15}
}

func (x *Metadata) GetEventTimes() map[string]*command.TimeInterval {
	if x != nil {
		return x.EventTimes
	}
	return nil
}

func (x *Metadata) GetEnvironment() []string {
	if x != nil {
		return x.Environment
	}
	return nil
}

var File_api_proxy_proxy_proto protoreflect.FileDescriptor

const file_api_proxy_proxy_proto_rawDesc = "" +
	"\n" +
	"\x15api/proxy/proxy.proto\x12\x05proxy\x1a\x1cgo/api/command/command.proto\x1a\x11api/log/log.proto\x1a\x15api/stats/stats.proto\"\x11\n" +
	"\x0fShutdownRequest\"6\n" +
	"\x10ShutdownResponse\x12\"\n" +
	"\x05stats\x18\x01 \x01(\v2\f.stats.StatsR\x05stats\"\x19\n" +
	"\x17GetStatusSummaryRequest\"\x8f\x02\n" +
	"\x18GetStatusSummaryResponse\x12o\n" +
	"\x16completed_action_stats\x18\x01 \x03(\v29.proxy.GetStatusSummaryResponse.CompletedActionStatsEntryR\x14completedActionStats\x12'\n" +
	"\x0frunning_actions\x18\x02 \x01(\x05R\x0erunningActions\x12\x10\n" +
	"\x03qps\x18\x03 \x01(\x05R\x03qps\x1aG\n" +
	"\x19CompletedActionStatsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\"\x13\n" +
	"\x11GetRecordsRequest\">\n" +
	"\x12GetRecordsResponse\x12(\n" +
	"\arecords\x18\x01 \x03(\v2\x0e.log.LogRecordR\arecords\"\xb8\x01\n" +
	"\x15AddProxyEventsRequest\x12M\n" +
	"\vevent_times\x18\x01 \x03(\v2,.proxy.AddProxyEventsRequest.EventTimesEntryR\n" +
	"eventTimes\x1aP\n" +
	"\x0fEventTimesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12'\n" +
	"\x05value\x18\x02 \x01(\v2\x11.cmd.TimeIntervalR\x05value:\x028\x01\"\x18\n" +
	"\x16AddProxyEventsResponse\"\xc9\x02\n" +
	"\n" +
	"RunRequest\x12&\n" +
	"\acommand\x18\x01 \x01(\v2\f.cmd.CommandR\acommand\x125\n" +
	"\x06labels\x18\x02 \x03(\v2\x1d.proxy.RunRequest.LabelsEntryR\x06labels\x12I\n" +
	"\x11execution_options\x18\x03 \x01(\v2\x1c.proxy.ProxyExecutionOptionsR\x10executionOptions\x12+\n" +
	"\bmetadata\x18\x04 \x01(\v2\x0f.proxy.MetadataR\bmetadata\x12)\n" +
	"\x10toolchain_inputs\x18\x05 \x03(\tR\x0ftoolchainInputs\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x88\x02\n" +
	"\vRunResponse\x12\x16\n" +
	"\x06stdout\x18\x01 \x01(\fR\x06stdout\x12\x16\n" +
	"\x06stderr\x18\x02 \x01(\fR\x06stderr\x12*\n" +
	"\x06result\x18\x03 \x01(\v2\x12.cmd.CommandResultR\x06result\x12!\n" +
	"\fexecution_id\x18\x04 \x01(\tR\vexecutionId\x12-\n" +
	"\n" +
	"action_log\x18\x05 \x01(\v2\x0e.log.LogRecordR\tactionLog\x12K\n" +
	"\x14remote_fallback_info\x18\x06 \x01(\v2\x19.proxy.RemoteFallbackInfoR\x12remoteFallbackInfo\"\xa6\x01\n" +
	"\x12RemoteFallbackInfo\x12\x1b\n" +
	"\texit_code\x18\x01 \x01(\x05R\bexitCode\x12\x16\n" +
	"\x06stdout\x18\x02 \x01(\fR\x06stdout\x12\x16\n" +
	"\x06stderr\x18\x03 \x01(\fR\x06stderr\x12C\n" +
	"\rresult_status\x18\x04 \x01(\x0e2\x1e.cmd.CommandResultStatus.ValueR\fresultStatus\"\xb5\x05\n" +
	"\x15ProxyExecutionOptions\x12M\n" +
	"\x12execution_strategy\x18\x01 \x01(\x0e2\x1e.proxy.ExecutionStrategy.ValueR\x11executionStrategy\x12W\n" +
	"\x18remote_execution_options\x18\x02 \x01(\v2\x1d.proxy.RemoteExecutionOptionsR\x16remoteExecutionOptions\x12T\n" +
	"\x17local_execution_options\x18\x03 \x01(\v2\x1c.proxy.LocalExecutionOptionsR\x15localExecutionOptions\x12,\n" +
	"\x12compare_with_local\x18\x04 \x01(\bR\x10compareWithLocal\x129\n" +
	"\x19num_retries_if_mismatched\x18\x05 \x01(\x05R\x16numRetriesIfMismatched\x12(\n" +
	"\x10num_local_reruns\x18\x06 \x01(\x05R\x0enumLocalReruns\x12*\n" +
	"\x11num_remote_reruns\x18\a \x01(\x05R\x0fnumRemoteReruns\x12'\n" +
	"\x0flog_environment\x18\b \x01(\bR\x0elogEnvironment\x12,\n" +
	"\x12include_action_log\x18\t \x01(\bR\x10includeActionLog\x12)\n" +
	"\x10reclient_timeout\x18\n" +
	" \x01(\x05R\x0freclientTimeout\x126\n" +
	"\x17enable_atomic_downloads\x18\v \x01(\bR\x15enableAtomicDownloads\x12%\n" +
	"\x0edownload_regex\x18\f \x01(\tR\rdownloadRegex\"k\n" +
	"\x11ExecutionStrategy\"V\n" +
	"\x05Value\x12\x0f\n" +
	"\vUNSPECIFIED\x10\x00\x12\t\n" +
	"\x05LOCAL\x10\x01\x12\n" +
	"\n" +
	"\x06REMOTE\x10\x02\x12\x19\n" +
	"\x15REMOTE_LOCAL_FALLBACK\x10\x03\x12\n" +
	"\n" +
	"\x06RACING\x10\x04\"\x80\x02\n" +
	"\x15LocalExecutionOptions\x12O\n" +
	"\bplatform\x18\x01 \x01(\x0e23.proxy.LocalExecutionOptions.LocalExecutionPlatformR\bplatform\x12 \n" +
	"\fdo_not_cache\x18\x02 \x01(\bR\n" +
	"doNotCache\x12#\n" +
	"\raccept_cached\x18\x03 \x01(\bR\facceptCached\x12\x18\n" +
	"\awrapper\x18\x04 \x01(\tR\awrapper\"5\n" +
	"\x16LocalExecutionPlatform\x12\x0f\n" +
	"\vUNSPECIFIED\x10\x00\x12\n" +
	"\n" +
	"\x06DOCKER\x10\x01\"\xab\x02\n" +
	"\x16RemoteExecutionOptions\x12#\n" +
	"\raccept_cached\x18\x01 \x01(\bR\facceptCached\x12 \n" +
	"\fdo_not_cache\x18\x02 \x01(\bR\n" +
	"doNotCache\x12)\n" +
	"\x10download_outputs\x18\x03 \x01(\bR\x0fdownloadOutputs\x12\x18\n" +
	"\awrapper\x18\x05 \x01(\tR\awrapper\x128\n" +
	"\x18canonicalize_working_dir\x18\x06 \x01(\bR\x16canonicalizeWorkingDir\x12E\n" +
	"\x1fpreserve_unchanged_output_mtime\x18\a \x01(\bR\x1cpreserveUnchangedOutputMtimeJ\x04\b\x04\x10\x05\"\xc0\x01\n" +
	"\bMetadata\x12@\n" +
	"\vevent_times\x18\x01 \x03(\v2\x1f.proxy.Metadata.EventTimesEntryR\n" +
	"eventTimes\x12 \n" +
	"\venvironment\x18\x02 \x03(\tR\venvironment\x1aP\n" +
	"\x0fEventTimesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12'\n" +
	"\x05value\x18\x02 \x01(\v2\x11.cmd.TimeIntervalR\x05value:\x028\x012\x80\x01\n" +
	"\bCommands\x125\n" +
	"\n" +
	"RunCommand\x12\x11.proxy.RunRequest\x1a\x12.proxy.RunResponse\"\x00\x12=\n" +
	"\bShutdown\x12\x16.proxy.ShutdownRequest\x1a\x17.proxy.ShutdownResponse\"\x002\x9d\x01\n" +
	"\x05Stats\x12C\n" +
	"\n" +
	"GetRecords\x12\x18.proxy.GetRecordsRequest\x1a\x19.proxy.GetRecordsResponse\"\x00\x12O\n" +
	"\x0eAddProxyEvents\x12\x1c.proxy.AddProxyEventsRequest\x1a\x1d.proxy.AddProxyEventsResponse\"\x002_\n" +
	"\x06Status\x12U\n" +
	"\x10GetStatusSummary\x12\x1e.proxy.GetStatusSummaryRequest\x1a\x1f.proxy.GetStatusSummaryResponse\"\x00B*Z(github.com/bazelbuild/reclient/api/proxyb\x06proto3"

var (
	file_api_proxy_proxy_proto_rawDescOnce sync.Once
	file_api_proxy_proxy_proto_rawDescData []byte
)

func file_api_proxy_proxy_proto_rawDescGZIP() []byte {
	file_api_proxy_proxy_proto_rawDescOnce.Do(func() {
		file_api_proxy_proxy_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proxy_proxy_proto_rawDesc), len(file_api_proxy_proxy_proto_rawDesc)))
	})
	return file_api_proxy_proxy_proto_rawDescData
}

var file_api_proxy_proxy_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_api_proxy_proxy_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_api_proxy_proxy_proto_goTypes = []any{
	(ExecutionStrategy_Value)(0),                      // 0: proxy.ExecutionStrategy.Value
	(LocalExecutionOptions_LocalExecutionPlatform)(0), // 1: proxy.LocalExecutionOptions.LocalExecutionPlatform
	(*ShutdownRequest)(nil),                           // 2: proxy.ShutdownRequest
	(*ShutdownResponse)(nil),                          // 3: proxy.ShutdownResponse
	(*GetStatusSummaryRequest)(nil),                   // 4: proxy.GetStatusSummaryRequest
	(*GetStatusSummaryResponse)(nil),                  // 5: proxy.GetStatusSummaryResponse
	(*GetRecordsRequest)(nil),                         // 6: proxy.GetRecordsRequest
	(*GetRecordsResponse)(nil),                        // 7: proxy.GetRecordsResponse
	(*AddProxyEventsRequest)(nil),                     // 8: proxy.AddProxyEventsRequest
	(*AddProxyEventsResponse)(nil),                    // 9: proxy.AddProxyEventsResponse
	(*RunRequest)(nil),                                // 10: proxy.RunRequest
	(*RunResponse)(nil),                               // 11: proxy.RunResponse
	(*RemoteFallbackInfo)(nil),                        // 12: proxy.RemoteFallbackInfo
	(*ProxyExecutionOptions)(nil),                     // 13: proxy.ProxyExecutionOptions
	(*ExecutionStrategy)(nil),                         // 14: proxy.ExecutionStrategy
	(*LocalExecutionOptions)(nil),                     // 15: proxy.LocalExecutionOptions
	(*RemoteExecutionOptions)(nil),                    // 16: proxy.RemoteExecutionOptions
	(*Metadata)(nil),                                  // 17: proxy.Metadata
	nil,                                               // 18: proxy.GetStatusSummaryResponse.CompletedActionStatsEntry
	nil,                                               // 19: proxy.AddProxyEventsRequest.EventTimesEntry
	nil,                                               // 20: proxy.RunRequest.LabelsEntry
	nil,                                               // 21: proxy.Metadata.EventTimesEntry
	(*stats.Stats)(nil),                               // 22: stats.Stats
	(*log.LogRecord)(nil),                             // 23: log.LogRecord
	(*command.Command)(nil),                           // 24: cmd.Command
	(*command.CommandResult)(nil),                     // 25: cmd.CommandResult
	(command.CommandResultStatus_Value)(0),            // 26: cmd.CommandResultStatus.Value
	(*command.TimeInterval)(nil),                      // 27: cmd.TimeInterval
}
var file_api_proxy_proxy_proto_depIdxs = []int32{
	22, // 0: proxy.ShutdownResponse.stats:type_name -> stats.Stats
	18, // 1: proxy.GetStatusSummaryResponse.completed_action_stats:type_name -> proxy.GetStatusSummaryResponse.CompletedActionStatsEntry
	23, // 2: proxy.GetRecordsResponse.records:type_name -> log.LogRecord
	19, // 3: proxy.AddProxyEventsRequest.event_times:type_name -> proxy.AddProxyEventsRequest.EventTimesEntry
	24, // 4: proxy.RunRequest.command:type_name -> cmd.Command
	20, // 5: proxy.RunRequest.labels:type_name -> proxy.RunRequest.LabelsEntry
	13, // 6: proxy.RunRequest.execution_options:type_name -> proxy.ProxyExecutionOptions
	17, // 7: proxy.RunRequest.metadata:type_name -> proxy.Metadata
	25, // 8: proxy.RunResponse.result:type_name -> cmd.CommandResult
	23, // 9: proxy.RunResponse.action_log:type_name -> log.LogRecord
	12, // 10: proxy.RunResponse.remote_fallback_info:type_name -> proxy.RemoteFallbackInfo
	26, // 11: proxy.RemoteFallbackInfo.result_status:type_name -> cmd.CommandResultStatus.Value
	0,  // 12: proxy.ProxyExecutionOptions.execution_strategy:type_name -> proxy.ExecutionStrategy.Value
	16, // 13: proxy.ProxyExecutionOptions.remote_execution_options:type_name -> proxy.RemoteExecutionOptions
	15, // 14: proxy.ProxyExecutionOptions.local_execution_options:type_name -> proxy.LocalExecutionOptions
	1,  // 15: proxy.LocalExecutionOptions.platform:type_name -> proxy.LocalExecutionOptions.LocalExecutionPlatform
	21, // 16: proxy.Metadata.event_times:type_name -> proxy.Metadata.EventTimesEntry
	27, // 17: proxy.AddProxyEventsRequest.EventTimesEntry.value:type_name -> cmd.TimeInterval
	27, // 18: proxy.Metadata.EventTimesEntry.value:type_name -> cmd.TimeInterval
	10, // 19: proxy.Commands.RunCommand:input_type -> proxy.RunRequest
	2,  // 20: proxy.Commands.Shutdown:input_type -> proxy.ShutdownRequest
	6,  // 21: proxy.Stats.GetRecords:input_type -> proxy.GetRecordsRequest
	8,  // 22: proxy.Stats.AddProxyEvents:input_type -> proxy.AddProxyEventsRequest
	4,  // 23: proxy.Status.GetStatusSummary:input_type -> proxy.GetStatusSummaryRequest
	11, // 24: proxy.Commands.RunCommand:output_type -> proxy.RunResponse
	3,  // 25: proxy.Commands.Shutdown:output_type -> proxy.ShutdownResponse
	7,  // 26: proxy.Stats.GetRecords:output_type -> proxy.GetRecordsResponse
	9,  // 27: proxy.Stats.AddProxyEvents:output_type -> proxy.AddProxyEventsResponse
	5,  // 28: proxy.Status.GetStatusSummary:output_type -> proxy.GetStatusSummaryResponse
	24, // [24:29] is the sub-list for method output_type
	19, // [19:24] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_api_proxy_proxy_proto_init() }
func file_api_proxy_proxy_proto_init() {
	if File_api_proxy_proxy_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proxy_proxy_proto_rawDesc), len(file_api_proxy_proxy_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_api_proxy_proxy_proto_goTypes,
		DependencyIndexes: file_api_proxy_proxy_proto_depIdxs,
		EnumInfos:         file_api_proxy_proxy_proto_enumTypes,
		MessageInfos:      file_api_proxy_proxy_proto_msgTypes,
	}.Build()
	File_api_proxy_proxy_proto = out.File
	file_api_proxy_proxy_proto_goTypes = nil
	file_api_proxy_proxy_proto_depIdxs = nil
}
