// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.1
// source: api/stats/stats.proto

package stats

import (
	log "github.com/bazelbuild/reclient/api/log"
	stat "github.com/bazelbuild/reclient/api/stat"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Stats struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	NumRecords         int64                  `protobuf:"varint,1,opt,name=num_records,json=numRecords,proto3" json:"num_records,omitempty"`
	Stats              []*stat.Stat           `protobuf:"bytes,2,rep,name=stats,proto3" json:"stats,omitempty"`
	Verification       *log.Verification      `protobuf:"bytes,4,opt,name=verification,proto3" json:"verification,omitempty"`
	ToolVersion        string                 `protobuf:"bytes,5,opt,name=tool_version,json=toolVersion,proto3" json:"tool_version,omitempty"`
	InvocationIds      []string               `protobuf:"bytes,6,rep,name=invocation_ids,json=invocationIds,proto3" json:"invocation_ids,omitempty"`
	MachineInfo        *MachineInfo           `protobuf:"bytes,7,opt,name=machine_info,json=machineInfo,proto3" json:"machine_info,omitempty"`
	ProxyInfo          []*log.ProxyInfo       `protobuf:"bytes,9,rep,name=proxy_info,json=proxyInfo,proto3" json:"proxy_info,omitempty"`
	BuildCacheHitRatio float64                `protobuf:"fixed64,10,opt,name=build_cache_hit_ratio,json=buildCacheHitRatio,proto3" json:"build_cache_hit_ratio,omitempty"`
	BuildLatency       float64                `protobuf:"fixed64,11,opt,name=build_latency,json=buildLatency,proto3" json:"build_latency,omitempty"`
	FatalExit          bool                   `protobuf:"varint,12,opt,name=fatal_exit,json=fatalExit,proto3" json:"fatal_exit,omitempty"`
	LogDirectories     []*LogDirectory        `protobuf:"bytes,13,rep,name=log_directories,json=logDirectories,proto3" json:"log_directories,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Stats) Reset() {
	*x = Stats{}
	mi := &file_api_stats_stats_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Stats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Stats) ProtoMessage() {}

func (x *Stats) ProtoReflect() protoreflect.Message {
	mi := &file_api_stats_stats_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Stats.ProtoReflect.Descriptor instead.
func (*Stats) Descriptor() ([]byte, []int) {
	return file_api_stats_stats_proto_rawDescGZIP(), []int{0}
}

func (x *Stats) GetNumRecords() int64 {
	if x != nil {
		return x.NumRecords
	}
	return 0
}

func (x *Stats) GetStats() []*stat.Stat {
	if x != nil {
		return x.Stats
	}
	return nil
}

func (x *Stats) GetVerification() *log.Verification {
	if x != nil {
		return x.Verification
	}
	return nil
}

func (x *Stats) GetToolVersion() string {
	if x != nil {
		return x.ToolVersion
	}
	return ""
}

func (x *Stats) GetInvocationIds() []string {
	if x != nil {
		return x.InvocationIds
	}
	return nil
}

func (x *Stats) GetMachineInfo() *MachineInfo {
	if x != nil {
		return x.MachineInfo
	}
	return nil
}

func (x *Stats) GetProxyInfo() []*log.ProxyInfo {
	if x != nil {
		return x.ProxyInfo
	}
	return nil
}

func (x *Stats) GetBuildCacheHitRatio() float64 {
	if x != nil {
		return x.BuildCacheHitRatio
	}
	return 0
}

func (x *Stats) GetBuildLatency() float64 {
	if x != nil {
		return x.BuildLatency
	}
	return 0
}

func (x *Stats) GetFatalExit() bool {
	if x != nil {
		return x.FatalExit
	}
	return false
}

func (x *Stats) GetLogDirectories() []*LogDirectory {
	if x != nil {
		return x.LogDirectories
	}
	return nil
}

type LogDirectory struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Digest        string                 `protobuf:"bytes,2,opt,name=digest,proto3" json:"digest,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogDirectory) Reset() {
	*x = LogDirectory{}
	mi := &file_api_stats_stats_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogDirectory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogDirectory) ProtoMessage() {}

func (x *LogDirectory) ProtoReflect() protoreflect.Message {
	mi := &file_api_stats_stats_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogDirectory.ProtoReflect.Descriptor instead.
func (*LogDirectory) Descriptor() ([]byte, []int) {
	return file_api_stats_stats_proto_rawDescGZIP(), []int{1}
}

func (x *LogDirectory) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *LogDirectory) GetDigest() string {
	if x != nil {
		return x.Digest
	}
	return ""
}

type MachineInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NumCpu        int64                  `protobuf:"varint,1,opt,name=num_cpu,json=numCpu,proto3" json:"num_cpu,omitempty"`
	RamMbs        int64                  `protobuf:"varint,2,opt,name=ram_mbs,json=ramMbs,proto3" json:"ram_mbs,omitempty"`
	OsFamily      string                 `protobuf:"bytes,3,opt,name=os_family,json=osFamily,proto3" json:"os_family,omitempty"`
	Arch          string                 `protobuf:"bytes,4,opt,name=arch,proto3" json:"arch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MachineInfo) Reset() {
	*x = MachineInfo{}
	mi := &file_api_stats_stats_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MachineInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MachineInfo) ProtoMessage() {}

func (x *MachineInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_stats_stats_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MachineInfo.ProtoReflect.Descriptor instead.
func (*MachineInfo) Descriptor() ([]byte, []int) {
	return file_api_stats_stats_proto_rawDescGZIP(), []int{2}
}

func (x *MachineInfo) GetNumCpu() int64 {
	if x != nil {
		return x.NumCpu
	}
	return 0
}

func (x *MachineInfo) GetRamMbs() int64 {
	if x != nil {
		return x.RamMbs
	}
	return 0
}

func (x *MachineInfo) GetOsFamily() string {
	if x != nil {
		return x.OsFamily
	}
	return ""
}

func (x *MachineInfo) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

var File_api_stats_stats_proto protoreflect.FileDescriptor

const file_api_stats_stats_proto_rawDesc = "" +
	"\n" +
	"\x15api/stats/stats.proto\x12\x05stats\x1a\x11api/log/log.proto\x1a\x13api/stat/stat.proto\"\xf3\x03\n" +
	"\x05Stats\x12\x1f\n" +
	"\vnum_records\x18\x01 \x01(\x03R\n" +
	"numRecords\x12!\n" +
	"\x05stats\x18\x02 \x03(\v2\v.stats.StatR\x05stats\x125\n" +
	"\fverification\x18\x04 \x01(\v2\x11.log.VerificationR\fverification\x12!\n" +
	"\ftool_version\x18\x05 \x01(\tR\vtoolVersion\x12%\n" +
	"\x0einvocation_ids\x18\x06 \x03(\tR\rinvocationIds\x125\n" +
	"\fmachine_info\x18\a \x01(\v2\x12.stats.MachineInfoR\vmachineInfo\x12-\n" +
	"\n" +
	"proxy_info\x18\t \x03(\v2\x0e.log.ProxyInfoR\tproxyInfo\x121\n" +
	"\x15build_cache_hit_ratio\x18\n" +
	" \x01(\x01R\x12buildCacheHitRatio\x12#\n" +
	"\rbuild_latency\x18\v \x01(\x01R\fbuildLatency\x12\x1d\n" +
	"\n" +
	"fatal_exit\x18\f \x01(\bR\tfatalExit\x12<\n" +
	"\x0flog_directories\x18\r \x03(\v2\x13.stats.LogDirectoryR\x0elogDirectoriesJ\x04\b\x03\x10\x04J\x04\b\b\x10\t\":\n" +
	"\fLogDirectory\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x16\n" +
	"\x06digest\x18\x02 \x01(\tR\x06digest\"p\n" +
	"\vMachineInfo\x12\x17\n" +
	"\anum_cpu\x18\x01 \x01(\x03R\x06numCpu\x12\x17\n" +
	"\aram_mbs\x18\x02 \x01(\x03R\x06ramMbs\x12\x1b\n" +
	"\tos_family\x18\x03 \x01(\tR\bosFamily\x12\x12\n" +
	"\x04arch\x18\x04 \x01(\tR\x04archB*Z(github.com/bazelbuild/reclient/api/statsb\x06proto3"

var (
	file_api_stats_stats_proto_rawDescOnce sync.Once
	file_api_stats_stats_proto_rawDescData []byte
)

func file_api_stats_stats_proto_rawDescGZIP() []byte {
	file_api_stats_stats_proto_rawDescOnce.Do(func() {
		file_api_stats_stats_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_stats_stats_proto_rawDesc), len(file_api_stats_stats_proto_rawDesc)))
	})
	return file_api_stats_stats_proto_rawDescData
}

var file_api_stats_stats_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_api_stats_stats_proto_goTypes = []any{
	(*Stats)(nil),            // 0: stats.Stats
	(*LogDirectory)(nil),     // 1: stats.LogDirectory
	(*MachineInfo)(nil),      // 2: stats.MachineInfo
	(*stat.Stat)(nil),        // 3: stats.Stat
	(*log.Verification)(nil), // 4: log.Verification
	(*log.ProxyInfo)(nil),    // 5: log.ProxyInfo
}
var file_api_stats_stats_proto_depIdxs = []int32{
	3, // 0: stats.Stats.stats:type_name -> stats.Stat
	4, // 1: stats.Stats.verification:type_name -> log.Verification
	2, // 2: stats.Stats.machine_info:type_name -> stats.MachineInfo
	5, // 3: stats.Stats.proxy_info:type_name -> log.ProxyInfo
	1, // 4: stats.Stats.log_directories:type_name -> stats.LogDirectory
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_api_stats_stats_proto_init() }
func file_api_stats_stats_proto_init() {
	if File_api_stats_stats_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_stats_stats_proto_rawDesc), len(file_api_stats_stats_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_stats_stats_proto_goTypes,
		DependencyIndexes: file_api_stats_stats_proto_depIdxs,
		MessageInfos:      file_api_stats_stats_proto_msgTypes,
	}.Build()
	File_api_stats_stats_proto = out.File
	file_api_stats_stats_proto_goTypes = nil
	file_api_stats_stats_proto_depIdxs = nil
}
