// THIS FILE IS AUTO GENERATED BY `bazel run //api:go_mod_tidy`
module github.com/bazelbuild/reclient/api

go 1.19

require (
	github.com/GoogleCloudPlatform/protoc-gen-bq-schema v0.0.0-20190119112626-026f9fcdf705
	github.com/bazelbuild/remote-apis-sdks v0.0.0-20240522145720-89b6d6b399ad
	google.golang.org/grpc v1.58.0-dev.0.20230804151048-7aceafcc52f9
	google.golang.org/protobuf v1.33.0
)

require (
	github.com/golang/protobuf v1.5.3 // indirect
	golang.org/x/net v0.23.0 // indirect
	golang.org/x/sys v0.18.0 // indirect
	golang.org/x/text v0.14.0 // indirect
	google.golang.org/genproto/googleapis/rpc v0.0.0-20230731190214-cbb8c96f2d6d // indirect
)
